
name: Build

on:
  workflow_dispatch:
  #push:
    #branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Begin
      run: |
        chmod +x ./main/otfcc/*
        python3 ./build.py
    - uses: actions/upload-artifact@v3
      with:
        name: XiaoheSimplifySans
        path: XiaoheSimplifySans.7z
    - uses: actions/upload-artifact@v3
      with:
        name: XiaoheSimplifySerif
        path: XiaoheSimplifySerif.7z
        
    - name: Upload to release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "test-release"
        prerelease: true
        draft: true
        title: Build Test
        files: |
            XiaoheSimplifySerif.7z
            XiaoheSimplifySerif.7z
